apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ai-k8s-console
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: aik8sconsole
        image: dockeraccount/aik8sconsole:latest
        ports:
        - containerPort: 80
        env:
        - name: APPINSIGHTS_INSTRUMENTATIONKEY
          value: your-application-instrumentation-key
