apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-example
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: k8s-web
          # Please update to use your own image in the container registry.
          image: dockeraccount/ai-k8s-app:0.0.1
          ports:
            - containerPort: 80
          env:
          # Uncomment the following lines to overwrite the Applicaiton Insights Instrumentation Key
          #- name: APPINSIGHTS_INSTRUMENTATIONKEY
          #  value: APPLICATION INSIGHTS KEY OVERWRITE 
          - name: ASPNETCORE_HOSTINGSTARTUPASSEMBLIES
            value: Microsoft.ApplicationInsights.Kubernetes.HostingStartup
          readinessProbe:
            httpGet:
              path: /Home/About
              port: 80
            initialDelaySeconds: 10 #(10 seconds more than the default timeout)
            periodSeconds: 10
            failureThreshold: 10
            timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-example
  annotations:
    service.beta.kubernetes.io/external-traffic: OnlyLocal
spec:
  ports:
    - name: http-port
      port: 80
      targetPort: 80
  selector:
    app: webapp
  type: LoadBalancer
