apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ai-k8s-multi-ikey
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: ai-k8s-multi-ikey-container
        image: dockeraccount/aik8sbasic:latest
        ports:
        - containerPort: 80
        env:
        - name: APPINSIGHTS_INSTRUMENTATIONKEY
          value: 5789ad10-8b39-4f8a-88dc-632d1342d5e0
---
apiVersion: v1
kind: Service
metadata:
  name: ai-k8s-multi-ikey
  annotations:
    service.beta.kubernetes.io/external-traffic: OnlyLocal
spec:
  ports:
  - name: http-port
    port: 80
    targetPort: 80
  selector:
    app: webapp
  type: LoadBalancer